FROM alpine:latest

RUN apk add --update make bash go git gnupg

RUN gpg --keyserver hkp://pool.sks-keyservers.net --recv-key 51852D87348FFC4C

ENV GOPATH=/go

RUN [ -d $GOPATH/src/github.com/hashicorp ] || mkdir -p $GOPATH/src/github.com/hashicorp
WORKDIR /go/src/github.com/hashicorp
ARG TF_VERSION
RUN git clone git://github.com/hashicorp/terraform.git \
	&& cd terraform \
	&& git verify-tag v${TF_VERSION} \
	&& git checkout v${TF_VERSION} \
	&& go install \
	&& ln -s /go/bin/terraform /usr/local/bin/terraform

WORKDIR /
ENTRYPOINT ["/usr/local/bin/terraform"]
