FROM alpine:latest

ARG TF_VERSION

RUN apk update && apk add ca-certificates

WORKDIR /
ADD https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip /terraform.zip
RUN unzip terraform.zip \
	&& rm terraform.zip \
	&& install -Dm755 -t /usr/local/bin terraform \
	&& rm terraform
