FROM alpine:latest

RUN apk update && apk add ca-certificates
RUN apk add bash make gnupg zsh

# Download the hashicorp PGP key
COPY hashicorp-*.asc ./
RUN \
	bash -c '[ -e ~/.gnupg/public-keys.d ] || mkdir -p ~/.gnupg/public-keys.d' \
	&& zsh -c 'set -e; set -x; mkdir -p ~/.gnupg/public-keys.d; for f in hashicorp-*.asc(.); do gpg2 --import < "$f" || exit $?; done; rm hashicorp-*.asc(.)'

ARG TF_VERSION

WORKDIR /
ADD https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip /terraform_${TF_VERSION}_linux_amd64.zip
ADD https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_SHA256SUMS /terraform_${TF_VERSION}_SHA256SUMS
ADD https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_SHA256SUMS.sig /terraform_${TF_VERSION}_SHA256SUMS.sig
RUN gpg2 --verify-files terraform_${TF_VERSION}_SHA256SUMS.sig \
	&& bash -c 'sha256sum -c <(grep -F linux_amd64 < terraform_"${TF_VERSION}"_SHA256SUMS)' \
	&& zsh -c 'rm terraform_*SHA256SUMS{,.sig}(.N)' \
	&& mv terraform_${TF_VERSION}_linux_amd64.zip terraform.zip
RUN unzip terraform.zip \
	&& rm terraform.zip \
	&& install -Dm755 -t /usr/local/bin terraform \
	&& rm terraform
